# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('precio', models.IntegerField(max_length=4)),
                ('capacidad', models.IntegerField(max_length=6)),
                ('celular', models.CharField(max_length=9)),
                ('ubicacion', models.CharField(max_length=60)),
                ('comentario', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenjoda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to=None)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_jodas.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
