# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dni',
        ),
        migrations.AddField(
            model_name='evento',
            name='edad_min',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_fiesta',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='evento',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
