# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0003_auto_20170904_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenjoda',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_fiesta',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Imagenjoda',
        ),
    ]
