# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0005_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
