# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0006_auto_20171021_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
