# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0007_auto_20171030_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
