# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0008_auto_20171106_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad',
            field=models.IntegerField(default=None),
        ),
    ]
