# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_jodas', '0011_auto_20171117_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
